[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npm start"

[env]
NODE_ENV = "production"
PORT = { default = "4000" }

# Build configuration
[build.env]
NODE_ENV = "production"
